openapi: 3.0.0
info:
  title: API to get, create and update NOM configurations
  version: 0.1.0
  x-audience: external-public
  x-api-id: modify-nom-configs-062023
  description: |
    Use these APIs to get, create and update NOM configurations
  contact:
    name: team-order-management
    email: team-order-management@newstore.com
servers:
  - url: https://dodici.x.newstore.net/v0
security:
  - newStoreAccessToken: []
paths:
  /config/nom_configuration/release_toggles:
    get:
      summary: Get NOM release toggles
      operationId: listReleaseToggles
      responses:
        '200':
          description: Release toggles for NOM.
          content:
            application/json:
              example:
                value:
                  swapProducts: false
                  showOfflineOrders: false
                  showRequestRefund: false
                  showProductId: false
                  enableItemSwapAfterGracePeriod: false
                  enableManualRouting: false
                  viewOMSettings: false
                updated_at: '2021-07-13T20:18:25Z'
              schema:
                title: Schema for setting release toggles in NOM.
                type: object
                required:
                  - value
                  - updated_at
                properties:
                  value:
                    type: object
                    properties:
                      swapProducts:
                        type: boolean
                        description: >-
                          Defines if swapping products within the remorse period
                          is activated in NOM, defaults to false.
                      showOfflineOrders:
                        type: boolean
                        description: >-
                          Define if the offline orders tab is displayed and
                          offline orders are visible or not, defaults to false.
                        default: false
                      showRequestRefund:
                        type: boolean
                        description: >-
                          Defines if order refunds or appeasements are activated
                          in NOM, defaults to false.
                        default: false
                      showProductId:
                        type: boolean
                        description: >-
                          Defines if the Product ID is shown in Stock Levels and
                          Mispicked Stock views, CSV export on the Product Stock
                          view, defaults to false.
                        default: false
                      enableItemSwapAfterGracePeriod:
                        type: boolean
                        description: >-
                          Defines if item swap is visible or not in the list of
                          actions that can be applied to a product when handling
                          an exception for an on hold order.
                        default: false
                      enableManualRouting:
                        type: boolean
                        description: >-
                          Defines if manual routing is visible or not in the
                          list of actions that can be applied to a product when
                          handling an exception for an on hold order.
                        default: false
                      viewOMSettings:
                        type: boolean
                        description: >-
                          If true, users with the required permissions will have
                          access to edit their order management settings in NOM.
                        default: false
                  updated_at:
                    type: string
                    format: date-time
        '404':
          description: >-
            Config key does not exist (it is not a case when key exists but just
            not set)
        '500':
          description: Internal Server Error.
          content:
            application/problem+json:
              schema:
                title: Internal error response while getting config
                type: object
                required:
                  - message
                  - request_id
                properties:
                  message:
                    type: string
                    description: A human readable description of the error
                  request_id:
                    type: string
        default:
          description: Unexpected Error
      description: >
        Retrieves the release toggles for various features within NewStore
        Omnichannel Manager set up for the retailer.
    post:
      summary: Set NOM release toggles
      operationId: createReleaseToggles
      requestBody:
        content:
          application/json:
            example:
              value:
                swapProducts: false
                showOfflineOrders: false
                showRequestRefund: false
                showProductId: false
                enableItemSwapAfterGracePeriod: false
                enableManualRouting: false
                viewOMSettings: false
            schema:
              title: Schema for setting release toggles in NOM.
              type: object
              required:
                - value
              properties:
                value:
                  type: object
                  properties:
                    swapProducts:
                      type: boolean
                      description: >-
                        Defines if swapping products within the remorse period
                        is activated in NOM, defaults to false.
                    showOfflineOrders:
                      type: boolean
                      description: >-
                        Define if the offline orders tab is displayed and
                        offline orders are visible or not, defaults to false.
                      default: false
                    showRequestRefund:
                      type: boolean
                      description: >-
                        Defines if order refunds or appeasements are activated
                        in NOM, defaults to false.
                      default: false
                    showProductId:
                      type: boolean
                      description: >-
                        Defines if the Product ID is shown in Stock Levels and
                        Mispicked Stock views, CSV export on the Product Stock
                        view, defaults to false.
                      default: false
                    enableItemSwapAfterGracePeriod:
                      type: boolean
                      description: >-
                        Defines if item swap is visible or not in the list of
                        actions that can be applied to a product when handling
                        an exception for an on hold order.
                      default: false
                    enableManualRouting:
                      type: boolean
                      description: >-
                        Defines if manual routing is visible or not in the list
                        of actions that can be applied to a product when
                        handling an exception for an on hold order.
                      default: false
                    viewOMSettings:
                      type: boolean
                      description: >-
                        If true, users with the required permissions will have
                        access to edit their order management settings in NOM.
                      default: false
        required: true
      responses:
        '200':
          description: Release toggles for NOM.
          content:
            application/json:
              example:
                value:
                  swapProducts: false
                  showOfflineOrders: false
                  showRequestRefund: false
                  showProductId: false
                  enableItemSwapAfterGracePeriod: false
                  enableManualRouting: false
                  viewOMSettings: false
                updated_at: '2021-07-13T20:18:25Z'
              schema:
                title: Schema for setting release toggles in NOM.
                type: object
                required:
                  - value
                  - updated_at
                properties:
                  value:
                    type: object
                    properties:
                      swapProducts:
                        type: boolean
                        description: >-
                          Defines if swapping products within the remorse period
                          is activated in NOM, defaults to false.
                      showOfflineOrders:
                        type: boolean
                        description: >-
                          Define if the offline orders tab is displayed and
                          offline orders are visible or not, defaults to false.
                        default: false
                      showRequestRefund:
                        type: boolean
                        description: >-
                          Defines if order refunds or appeasements are activated
                          in NOM, defaults to false.
                        default: false
                      showProductId:
                        type: boolean
                        description: >-
                          Defines if the Product ID is shown in Stock Levels and
                          Mispicked Stock views, CSV export on the Product Stock
                          view, defaults to false.
                        default: false
                      enableItemSwapAfterGracePeriod:
                        type: boolean
                        description: >-
                          Defines if item swap is visible or not in the list of
                          actions that can be applied to a product when handling
                          an exception for an on hold order.
                        default: false
                      enableManualRouting:
                        type: boolean
                        description: >-
                          Defines if manual routing is visible or not in the
                          list of actions that can be applied to a product when
                          handling an exception for an on hold order.
                        default: false
                      viewOMSettings:
                        type: boolean
                        description: >-
                          If true, users with the required permissions will have
                          access to edit their order management settings in NOM.
                        default: false
                  updated_at:
                    type: string
                    format: date-time
        '400':
          description: Incorrect payload for config (validation failed).
          content:
            application/problem+json:
              schema:
                title: Config validation/parsing failed
                type: object
                required:
                  - messages
                  - request_id
                properties:
                  messages:
                    type: array
                    description: A list of validation errors
                    items:
                      type: string
                      description: >-
                        An validation/parsing error which explains why we can't
                        set this config
                  request_id:
                    type: string
        '409':
          description: Update failed for config due to lost race.
        '500':
          description: Internal Server Error.
          content:
            application/problem+json:
              schema:
                title: Internal error response while getting config
                type: object
                required:
                  - message
                  - request_id
                properties:
                  message:
                    type: string
                    description: A human readable description of the error
                  request_id:
                    type: string
        default:
          description: Unexpected Error
      description: >
        Sets release toggles for various features within NewStore Omnichannel
        Manager for the retailer.

        This action overwrites any existing configuration and doesn't allow for
        partial updates.
  /config/nom_configuration/order_tracking_urls:
    get:
      summary: Retrieve order tracking URLs config for NOM.
      operationId: listOrderTrackingUrls
      responses:
        '200':
          description: Order tracking URLs for NOM.
          content:
            application/json:
              example:
                value:
                  gls: https://gls-group.eu/EU/en/parcel-tracking?match=
                  ups: >-
                    https://www.fedex.com/apps/fedextrack/?action=track&trackingnumber=
                updated_at: '2021-07-13T20:18:25Z'
              schema:
                title: >-
                  Schema for the default tracking URLs of the used shipping
                  carriers.
                type: object
                required:
                  - value
                  - updated_at
                properties:
                  value:
                    type: object
                    description: This value contains the order tracking url configurations.
                    properties:
                      additionalProperties:
                        type: object
                        description: >-
                          The key of this object is the shipping carrier such as
                          DHL or FedEx. The value is the URL to the tracking
                          website of the shipping carrier.
                  updated_at:
                    type: string
                    format: date-time
        '404':
          description: >-
            Config key does not exist (it is not a case when key exists but just
            not set)
        '500':
          description: Internal Server Error.
          content:
            application/problem+json:
              schema:
                title: Internal error response while getting config
                type: object
                required:
                  - message
                  - request_id
                properties:
                  message:
                    type: string
                    description: A human readable description of the error
                  request_id:
                    type: string
        default:
          description: Unexpected Error
      description: |
        Retrieves the order tracking URLs for NewStore Omnichannel Manager.
    post:
      summary: Set NOM order tracking URLs
      operationId: createOrderTrackingUrls
      requestBody:
        content:
          application/json:
            example:
              value:
                gls: https://gls-group.eu/EU/en/parcel-tracking?match=
                ups: >-
                  https://www.fedex.com/apps/fedextrack/?action=track&trackingnumber=
            schema:
              title: >-
                Schema for the default tracking URLs of the used shipping
                carriers.
              type: object
              required:
                - value
              properties:
                value:
                  type: object
                  description: This value contains the order tracking url configurations.
                  properties:
                    additionalProperties:
                      type: object
                      description: >-
                        The key of this object is the shipping carrier such as
                        DHL or FedEx. The value is the URL to the tracking
                        website of the shipping carrier.
        required: true
      responses:
        '200':
          description: Order tracking URLs for NOM.
          content:
            application/problem+json:
              example:
                value:
                  gls: https://gls-group.eu/EU/en/parcel-tracking?match=
                  ups: >-
                    https://www.fedex.com/apps/fedextrack/?action=track&trackingnumber=
                updated_at: '2021-07-13T20:18:25Z'
              schema:
                title: >-
                  Schema for the default tracking URLs of the used shipping
                  carriers.
                type: object
                required:
                  - value
                  - updated_at
                properties:
                  value:
                    type: object
                    description: This value contains the order tracking url configurations.
                    properties:
                      additionalProperties:
                        type: object
                        description: >-
                          The key of this object is the shipping carrier such as
                          DHL or FedEx. The value is the URL to the tracking
                          website of the shipping carrier.
                  updated_at:
                    type: string
                    format: date-time
        '400':
          description: Incorrect payload for config (validation failed).
          content:
            application/problem+json:
              schema:
                title: Config validation/parsing failed
                type: object
                required:
                  - messages
                  - request_id
                properties:
                  messages:
                    type: array
                    description: A list of validation errors
                    items:
                      type: string
                      description: >-
                        An validation/parsing error which explains why we can't
                        set this config
                  request_id:
                    type: string
        '409':
          description: Update failed for config due to lost race.
        '500':
          description: Internal Server Error.
          content:
            application/problem+json:
              schema:
                title: Internal error response while getting config
                type: object
                required:
                  - message
                  - request_id
                properties:
                  message:
                    type: string
                    description: A human readable description of the error
                  request_id:
                    type: string
        default:
          description: Unexpected Error
      description: >
        Sets the order tracking URLs for NewStore Omnichannel Manager.

        This action overwrites any existing configuration and doesn't allow for
        partial updates.


        **Important**: The shipping carrier must be provided in lower case. For
        example, 

        if you wish to provide a custom tracking URL for ``USPS``, use ``usps``
        as key.
  /config/nom_configuration/order_export:
    get:
      summary: Get order export configuration
      operationId: showOrderExport
      responses:
        '200':
          description: Defines configuration for the order export.
          content:
            application/json:
              example:
                value:
                  orderExtendedAttributes:
                    - name: sku
                      label: SKU
                    - name: ean13
                      label: EAN13
                  orderItemExtendedAttributes:
                    - name: sku
                      label: SKU
                    - name: ean13
                      label: EAN13
                  orderItemExternalIdentifiers:
                    - name: sku
                      label: SKU
                    - name: ean13
                      label: EAN13
                updated_at: '2021-07-13T20:18:25Z'
              schema:
                title: Schema for the order export configuration
                type: object
                required:
                  - value
                  - updated_at
                properties:
                  value:
                    type: object
                    properties:
                      orderExtendedAttributes:
                        type: array
                        description: >-
                          Defines an array of extended order attributes which
                          can be shown inside order export.
                        items:
                          type: object
                          required:
                            - label
                            - name
                          properties:
                            label:
                              type: string
                              description: >-
                                The string to be shown in order export for this
                                extended order attribute.
                            name:
                              type: string
                              description: >-
                                The system name of the extended order attribute.
                                Must match the name used for the extended order
                                attribute used in the order.
                          additionalProperties: false
                        minItems: 1
                      orderItemExtendedAttributes:
                        type: array
                        description: >-
                          Defines an array of extended order item attributes
                          which can be shown inside order export.
                        items:
                          type: object
                          required:
                            - label
                            - name
                          properties:
                            label:
                              type: string
                              description: >-
                                The string to be shown in order export for this
                                extended order item attribute.
                            name:
                              type: string
                              description: >-
                                The system name of the extended order item
                                attribute. Must match the name used for the
                                extended order item attribute used in the order.
                          additionalProperties: false
                        minItems: 1
                      orderItemExternalIdentifiers:
                        type: array
                        description: >-
                          Defines an array of external order item identifiers
                          which can be shown inside order export.
                        items:
                          type: object
                          required:
                            - label
                            - name
                          properties:
                            label:
                              type: string
                              description: >-
                                The string to be shown in order export for this
                                external order item identifier.
                            name:
                              type: string
                              description: >-
                                The system name of the external order item
                                identifier. Must match the name used for the
                                external order item identifier used in the
                                order.
                          additionalProperties: false
                        minItems: 1
                        default:
                          - label: SKU
                            name: sku
                          - label: EAN13
                            name: ean13
                  updated_at:
                    type: string
                    format: date-time
        '404':
          description: >-
            Config key does not exist (it is not a case when key exists but just
            not set)
        '500':
          description: Internal Server Error.
          content:
            application/problem+json:
              schema:
                title: Internal error response while getting config
                type: object
                required:
                  - message
                  - request_id
                properties:
                  message:
                    type: string
                    description: A human readable description of the error
                  request_id:
                    type: string
        default:
          description: Unexpected Error
      description: >
        Retrieves the configuration for an order export via [NewStore
        Omnichannel Manager](/product/nomapp/nom-export-orders).
    post:
      summary: Create order export configuration
      operationId: createOrderExport
      requestBody:
        content:
          application/json:
            example:
              value:
                orderExtendedAttributes:
                  - name: sku
                    label: SKU
                  - name: ean13
                    label: EAN13
                orderItemExtendedAttributes:
                  - name: sku
                    label: SKU
                  - name: ean13
                    label: EAN13
                orderItemExternalIdentifiers:
                  - name: sku
                    label: SKU
                  - name: ean13
                    label: EAN13
            schema:
              title: Schema for the order export configuration
              type: object
              required:
                - value
              properties:
                value:
                  type: object
                  properties:
                    orderExtendedAttributes:
                      type: array
                      description: >-
                        Defines an array of extended order attributes which can
                        be shown inside order export.
                      items:
                        type: object
                        required:
                          - label
                          - name
                        properties:
                          label:
                            type: string
                            description: >-
                              The string to be shown in order export for this
                              extended order attribute.
                          name:
                            type: string
                            description: >-
                              The system name of the extended order attribute.
                              Must match the name used for the extended order
                              attribute used in the order.
                        additionalProperties: false
                      minItems: 1
                    orderItemExtendedAttributes:
                      type: array
                      description: >-
                        Defines an array of extended order item attributes which
                        can be shown inside order export.
                      items:
                        type: object
                        required:
                          - label
                          - name
                        properties:
                          label:
                            type: string
                            description: >-
                              The string to be shown in order export for this
                              extended order item attribute.
                          name:
                            type: string
                            description: >-
                              The system name of the extended order item
                              attribute. Must match the name used for the
                              extended order item attribute used in the order.
                        additionalProperties: false
                      minItems: 1
                    orderItemExternalIdentifiers:
                      type: array
                      description: >-
                        Defines an array of external order item identifiers
                        which can be shown inside order export.
                      items:
                        type: object
                        required:
                          - label
                          - name
                        properties:
                          label:
                            type: string
                            description: >-
                              The string to be shown in order export for this
                              external order item identifier.
                          name:
                            type: string
                            description: >-
                              The system name of the external order item
                              identifier. Must match the name used for the
                              external order item identifier used in the order.
                        additionalProperties: false
                      minItems: 1
                      default:
                        - label: SKU
                          name: sku
                        - label: EAN13
                          name: ean13
        required: true
      responses:
        '200':
          description: Configuration for the order export.
          content:
            application/json:
              example:
                value:
                  orderExtendedAttributes:
                    - name: sku
                      label: SKU
                    - name: ean13
                      label: EAN13
                  orderItemExtendedAttributes:
                    - name: sku
                      label: SKU
                    - name: ean13
                      label: EAN13
                  orderItemExternalIdentifiers:
                    - name: sku
                      label: SKU
                    - name: ean13
                      label: EAN13
                updated_at: '2021-07-13T20:18:25Z'
              schema:
                title: Schema for the order export configuration
                type: object
                required:
                  - value
                  - updated_at
                properties:
                  value:
                    type: object
                    properties:
                      orderExtendedAttributes:
                        type: array
                        description: >-
                          Defines an array of extended order attributes which
                          can be shown inside order export.
                        items:
                          type: object
                          required:
                            - label
                            - name
                          properties:
                            label:
                              type: string
                              description: >-
                                The string to be shown in order export for this
                                extended order attribute.
                            name:
                              type: string
                              description: >-
                                The system name of the extended order attribute.
                                Must match the name used for the extended order
                                attribute used in the order.
                          additionalProperties: false
                        minItems: 1
                      orderItemExtendedAttributes:
                        type: array
                        description: >-
                          Defines an array of extended order item attributes
                          which can be shown inside order export.
                        items:
                          type: object
                          required:
                            - label
                            - name
                          properties:
                            label:
                              type: string
                              description: >-
                                The string to be shown in order export for this
                                extended order item attribute.
                            name:
                              type: string
                              description: >-
                                The system name of the extended order item
                                attribute. Must match the name used for the
                                extended order item attribute used in the order.
                          additionalProperties: false
                        minItems: 1
                      orderItemExternalIdentifiers:
                        type: array
                        description: >-
                          Defines an array of external order item identifiers
                          which can be shown inside order export.
                        items:
                          type: object
                          required:
                            - label
                            - name
                          properties:
                            label:
                              type: string
                              description: >-
                                The string to be shown in order export for this
                                external order item identifier.
                            name:
                              type: string
                              description: >-
                                The system name of the external order item
                                identifier. Must match the name used for the
                                external order item identifier used in the
                                order.
                          additionalProperties: false
                        minItems: 1
                        default:
                          - label: SKU
                            name: sku
                          - label: EAN13
                            name: ean13
                  updated_at:
                    type: string
                    format: date-time
        '400':
          description: Incorrect payload for config (validation failed).
          content:
            application/problem+json:
              schema:
                title: Config validation/parsing failed
                type: object
                required:
                  - messages
                  - request_id
                properties:
                  messages:
                    type: array
                    description: A list of validation errors
                    items:
                      type: string
                      description: >-
                        An validation/parsing error which explains why we can't
                        set this config
                  request_id:
                    type: string
        '409':
          description: Update failed for config due to lost race.
        '500':
          description: Internal Server Error.
          content:
            application/problem+json:
              schema:
                title: Internal error response while getting config
                type: object
                required:
                  - message
                  - request_id
                properties:
                  message:
                    type: string
                    description: A human readable description of the error
                  request_id:
                    type: string
        default:
          description: Unexpected Error
      description: >
        Creates the configuration to enable order exports via [NewStore
        Omnichannel Manager](/product/nomapp/nom-export-orders).

        This action overwrites any existing configuration and doesn't allow for
        partial updates.
  /config/nom_configuration/order_extended_attributes:
    get:
      summary: List extended order attributes
      operationId: listOrderExtendedAttributes
      responses:
        '200':
          description: >-
            An array of extended order attributes which can be shown on the
            order detail page.
          content:
            application/json:
              example:
                value:
                  - display: badge
                    label: >-
                      The string to be shown in NOM for this extended order
                      attribute
                    name: The system name of the extended order attribute
                  - display: string
                    label: >-
                      The string to be shown in NOM for this extended order
                      attribute
                    name: The system name of the extended order attribute
                updated_at: '2021-07-13T20:18:25Z'
              schema:
                title: >-
                  Schema for an array of extended order attributes which can be
                  shown on the order detail page.
                type: object
                required:
                  - value
                  - updated_at
                properties:
                  value:
                    type: object
                    properties:
                      display:
                        type: string
                        description: >-
                          Defines the way the extended order attribute will be
                          shown in NOM. Either as 'badge', simple 'string' or
                          link if set to 'url'.
                        enum:
                          - badge
                          - string
                          - url
                      label:
                        type: string
                        description: >-
                          The string to be shown in NOM for this extended order
                          attribute.
                      name:
                        type: string
                        description: >-
                          The system name of the extended order attribute. Must
                          match the name used for the extended order attribute
                          used in the order.
                  updated_at:
                    type: string
                    format: date-time
        '404':
          description: >-
            Config key does not exist (it is not a case when key exists but just
            not set)
        '500':
          description: Internal Server Error.
          content:
            application/problem+json:
              schema:
                title: Internal error response while getting config
                type: object
                required:
                  - message
                  - request_id
                properties:
                  message:
                    type: string
                    description: A human readable description of the error
                  request_id:
                    type: string
        default:
          description: Unexpected Error
      description: >
        Retrieves an array of extended order attributes which can be shown on
        the order detail page

        in NewStore Omnichannel Manager. For more information on the extended
        attributes,

        see [this
        section](/developers/configuration/config-order-detail-page/#displaying-extended-attributes).
    post:
      summary: Create extended order attributes
      operationId: createOrderExtendedAttributes
      requestBody:
        content:
          application/json:
            example:
              value:
                - display: badge
                  label: >-
                    The string to be shown in NOM for this extended order
                    attribute
                  name: The system name of the extended order attribute
                - display: string
                  label: >-
                    The string to be shown in NOM for this extended order
                    attribute
                  name: The system name of the extended order attribute
            schema:
              title: >-
                Schema for an array of extended order attributes which can be
                shown on the order detail page.
              type: object
              required:
                - value
              properties:
                value:
                  type: object
                  properties:
                    display:
                      type: string
                      description: >-
                        Defines the way the extended order attribute will be
                        shown in NOM. Either as 'badge', simple 'string' or link
                        if set to 'url'.
                      enum:
                        - badge
                        - string
                        - url
                    label:
                      type: string
                      description: >-
                        The string to be shown in NOM for this extended order
                        attribute.
                    name:
                      type: string
                      description: >-
                        The system name of the extended order attribute. Must
                        match the name used for the extended order attribute
                        used in the order.
        required: true
      responses:
        '200':
          description: >-
            An array of extended order attributes which can be shown on the
            order detail page.
          content:
            application/json:
              example:
                value:
                  - display: badge
                    label: >-
                      The string to be shown in NOM for this extended order
                      attribute
                    name: The system name of the extended order attribute
                  - display: string
                    label: >-
                      The string to be shown in NOM for this extended order
                      attribute
                    name: The system name of the extended order attribute
                updated_at: '2021-07-13T20:18:25Z'
              schema:
                title: >-
                  Schema for an array of extended order attributes which can be
                  shown on the order detail page.
                type: object
                required:
                  - value
                  - updated_at
                properties:
                  value:
                    type: object
                    properties:
                      display:
                        type: string
                        description: >-
                          Defines the way the extended order attribute will be
                          shown in NOM. Either as 'badge', simple 'string' or
                          link if set to 'url'.
                        enum:
                          - badge
                          - string
                          - url
                      label:
                        type: string
                        description: >-
                          The string to be shown in NOM for this extended order
                          attribute.
                      name:
                        type: string
                        description: >-
                          The system name of the extended order attribute. Must
                          match the name used for the extended order attribute
                          used in the order.
                  updated_at:
                    type: string
                    format: date-time
        '400':
          description: Incorrect payload for config (validation failed).
          content:
            application/problem+json:
              schema:
                title: Config validation/parsing failed
                type: object
                required:
                  - messages
                  - request_id
                properties:
                  messages:
                    type: array
                    description: A list of validation errors
                    items:
                      type: string
                      description: >-
                        An validation/parsing error which explains why we can't
                        set this config
                  request_id:
                    type: string
        '409':
          description: Update failed for config due to lost race.
        '500':
          description: Internal Server Error.
          content:
            application/problem+json:
              schema:
                title: Internal error response while getting config
                type: object
                required:
                  - message
                  - request_id
                properties:
                  message:
                    type: string
                    description: A human readable description of the error
                  request_id:
                    type: string
        default:
          description: Unexpected Error
      description: >
        Creates an array of extended order attributes which can be shown on the
        order detail page

        in NewStore Omnichannel Manager. For more information on the extended
        attributes,

        see [this
        section](/developers/configuration/config-order-detail-page/#displaying-extended-attributes).

        This action overwrites any existing configuration and doesn't allow for
        partial updates.
components:
  securitySchemes:
    newStoreAccessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
