openapi: 3.0.0
info:
  title: External Order Webhook
  version: 0.1.0
  x-audience: external-public
  x-api-id: external-order-webhook-062023
  description: >
    Requests order information from an external order management system.


    Use this webhook when you use an external order management system as your
    primary OMS and

    NewStore is the secondary order management system in your business. This
    webhook retrieves the

    full purchase history of a customer or order details from orders placed
    outside of the NewStore

    platform.


    To use this webhook, first set up the

    [external order webhook
    configuration](/newstore-cloud/order_management/sales_order_tenant_config.html#operation/post-external-order-webhook).


    For more information, see the [integration
    guide](developers/guides/order-management-routing/integ-eOMS).
  contact:
    name: team-order-management
    email: team-order-management@newstore.com
servers:
  - url: https://example.com/newstore_api/v0
paths:
  /orders:
    get:
      summary: Request purchase history details of a customer
      operationId: listCustomerPurchaseHistory
      responses:
        '200':
          description: Contains the list with the last 100 orders of the customer.
          content:
            application/json:
              example:
                orders:
                  - id: GD000001234
                    placed_at: '2021-11-22T12:51:39.30Z'
                    channel_type: web
                    origin: newstore
                    origin_id: 6f38b75f-3fb3-4454-975d-af0cb412f8fa
                    status: in_fulfillment
                    currency: USD
                    fulfillment_type: traditional
                    items:
                      - id: product-agd6f4
                        origin_id: b9a144c2-3bd2-4066-983e-b2f2aa0c23ee
                        status: in_fulfillment
                        price:
                          net: 80
                          tax: 8
                          gross: 88
                          discount: 0
                        product_attributes:
                          name: Kate Dress
                          size: M
                          color: red
                          image_url: https://image.com/dress.jpeg
                        external_identifier:
                          sku: '1000012'
                          serial_number: '7890'
                  - id: GD000001235
                    placed_at: '2021-11-20T08:11:39.30Z'
                    channel_type: store
                    origin: external
                    origin_id: GD000001234
                    status: complete
                    currency: USD
                    fulfillment_type: in_store_purchase
                    items:
                      - id: product-df45g6
                        origin_id: b9a144c2-3bd2-4066-983e-b2f2aa07y65d
                        status: complete
                        price:
                          net: 90
                          tax: 9
                          gross: 99
                          discount: 0
                        product_attributes:
                          name: Tote Bag
              schema:
                title: >-
                  Response body for getting a customers purchase history from an
                  external system, sorted in a descended order (newest orders
                  first)
                type: object
                required:
                  - orders
                properties:
                  orders:
                    description: >-
                      List of orders associated to the requested consumer.
                      Please note that the list should contain a maximum number
                      of 100 orders. The NewStore platform will cut off
                      everything over 100 orders.
                    type: array
                    items:
                      description: All common order and order item attributes.
                      type: object
                      required:
                        - id
                        - placed_at
                        - channel_type
                        - origin
                        - origin_id
                        - status
                        - currency
                        - fulfillment_type
                        - items
                      properties:
                        id:
                          type: string
                          minLength: 1
                          description: >-
                            The identifier of the order, it's the shared
                            identifier between NewStore and the external system.
                        placed_at:
                          type: string
                          format: date-time
                          description: >-
                            The time when the order was placed. It should follow
                            https://tools.ietf.org/html/rfc3339 in UTC.
                        channel_type:
                          type: string
                          enum:
                            - store
                            - web
                          minLength: 1
                          description: The channel through which the order was placed.
                        origin:
                          type: string
                          enum:
                            - newstore
                            - external
                          minLength: 1
                          description: >-
                            Describes in which Order Management System the order
                            originated from. [In-store
                            returns](https://docs.newstore.net/developers/guides/integ-eOMS/#in-store-returns)
                            are affected by the value of `origin`
                        origin_id:
                          type: string
                          minLength: 1
                          description: >-
                            The identifier of the order from the Order
                            Management System where it originated from. If it
                            originated in Newstore, it must be the UUID assigned
                            to the order during the order creation process.
                        status:
                          type: string
                          enum:
                            - pending
                            - in_fulfillment
                            - complete
                          minLength: 1
                          description: >-
                            The current status of the order. Specified as
                            `pending` when the order is in the grace period,
                            `in_fulfillment` if any of the item is currently
                            being fulfilled, and `complete` when the processing
                            of all items in the platform are considered
                            complete, such as when all items have been shipped,
                            canceled or returned.
                        currency:
                          type: string
                          minLength: 3
                          maxLength: 3
                          description: Currency code (ISO 4217) used in internal accounting
                        fulfillment_type:
                          type: string
                          enum:
                            - traditional
                            - same_day
                            - in_store_pickup
                            - in_store_purchase
                            - multiple
                          minLength: 1
                          description: >-
                            The fulfillment type of the order. In case of mixed
                            cart orders, fulfillment type is always 'multiple'
                        items:
                          type: array
                          minLength: 1
                          items:
                            type: object
                            required:
                              - id
                              - origin_id
                              - status
                              - price
                              - product_attributes
                            properties:
                              id:
                                type: string
                                minLength: 1
                                description: >-
                                  The identifier of the product, this can be any
                                  type of identifier from the external system
                                  and should be unique per order item.
                              origin_id:
                                type: string
                                minLength: 1
                                description: >-
                                  If the origin of the order is 'newstore', this
                                  should be the order item UUID. If the order
                                  originated in an external system, it should be
                                  the identifier from the external system and is
                                  the same as 'id'.
                              status:
                                type: string
                                enum:
                                  - pending
                                  - in_fulfillment
                                  - complete
                                  - cancelled
                                  - returned
                              price:
                                type: object
                                required:
                                  - gross
                                  - net
                                  - tax
                                  - discount
                                properties:
                                  gross:
                                    type: number
                                    description: The gross price of the item.
                                  net:
                                    type: number
                                    description: The net price of the item.
                                  tax:
                                    type: number
                                    description: The taxes of the item.
                                  discount:
                                    type: number
                                    description: The applied discount to the item.
                              product_attributes:
                                type: object
                                required:
                                  - name
                                properties:
                                  name:
                                    type: string
                                    minLength: 1
                                    description: The name of the product.
                                  size:
                                    type: string
                                    minLength: 1
                                    description: The size of the product.
                                  color:
                                    type: string
                                    minLength: 1
                                    description: The color of the product.
                                  image_url:
                                    type: string
                                    format: uri
                                    minLength: 1
                                    description: The URL to a product image.
                                  additional_variant_1:
                                    type: string
                                    minLength: 1
                                    description: >-
                                      A free form field for additional product
                                      attributes.
                                  additional_variant_2:
                                    type: string
                                    minLength: 1
                                    description: >-
                                      A free form field for additional product
                                      attributes.
                              external_identifier:
                                description: External identifiers for order item
                                type: object
                                properties:
                                  '*':
                                    description: >-
                                      Any external identifier as specified in
                                      the catalog data, e.g. SKU, EAN and
                                      others.
                                    type: string
                                    minLength: 1
                                  serial_number:
                                    description: Serial number for order item
                                    type: string
                                    minLength: 1
                                  product_id:
                                    description: >-
                                      The identifier of the product from the
                                      NewStore catalog.
                                    type: string
                                    minLength: 1
                              discounts:
                                type: array
                                description: A list of applied discounts
                                minLength: 1
                                items:
                                  type: object
                                  required:
                                    - level
                                    - value
                                    - price_adjustment
                                    - type
                                  properties:
                                    level:
                                      type: string
                                      enum:
                                        - item
                                        - order
                                      description: >-
                                        On which level the discount was applied,
                                        either on the entire order or only on
                                        this item.
                                    value:
                                      type: number
                                      minimum: 0
                                      description: >-
                                        If the discount is of type 'fixed', this
                                        is equal to the adjusted price amount.
                                        If the discount is of type 'percentage',
                                        this is the percentage, e.g. 20%.
                                    price_adjustment:
                                      type: number
                                      minimum: 0
                                      description: The applied discount.
                                    type:
                                      type: string
                                      enum:
                                        - fixed
                                        - percentage
                                      description: >-
                                        The type of the discount, either 'fixed'
                                        or 'percentage'.
        '400':
          description: The request to fetch customer history is malformed.
        '403':
          description: >-
            The request to fetch order details is unauthenticated or API Key is
            invalid.
        '500':
          description: >-
            Something went wrong on the server when requesting the purchase
            history of the customer.
        default:
          description: Unexpected Error
      description: >
        Retrieves the purchase history of a customer from an external system.


        This method returns a maximum of **100** orders, sorted from newest to
        oldest orders placed

        in the system. The NewStore platform will cut off everything over 100
        orders.


        The retrieved orders are filtered by the email address of the customer.
      parameters:
        - in: query
          name: consumer_email
          schema:
            type: string
          description: The email of the customer.
  /orders/{id}:
    get:
      summary: Request order details
      operationId: listOrderDetails
      responses:
        '200':
          description: Contains all order details.
          content:
            application/json:
              examples:
                Order with customer from external origin:
                  summary: Order originated in an external system.
                  value:
                    id: GD000001234
                    placed_at: '2021-11-22T12:51:39.30Z'
                    channel_type: web
                    origin: external
                    origin_id: GD000001234
                    status: in_fulfillment
                    currency: USD
                    fulfillment_type: traditional
                    customer:
                      id: e97f516a-8cce-447c-9757-8b54b84d8967
                      name: John Doe
                      email: johndoe@gmail.com
                    items:
                      - id: '394329361530903'
                        origin_id: '394329361530903'
                        status: in_fulfillment
                        price:
                          net: 72
                          tax: 7.2
                          gross: 79.2
                          discount: 10
                        product_attributes:
                          name: Kate Dress
                          size: M
                          color: red
                          image_url: https://image.com/dress.jpeg
                          additional_variant_1: Regular fit
                          additional_variant_2: Red with highlights
                        external_identifier:
                          sku: '1000016'
                          serial_number: SE-1234
                          product_id: '1000016'
                        discounts:
                          - level: item
                            value: 10
                            price_adjustment: 10
                            type: percentage
                    totals:
                      net: 72
                      tax: 7.2
                      gross: 79.2
                      total: 84.2
                      shipping: 5
                      discount: 10
                    payment_history:
                      - category: refund
                        amount: 77.58
                        currency: USD
                        method: cash
                      - category: payment
                        amount: 84.2
                        currency: USD
                        method: credit_card
                        payment_information: Visa (**** 1111)
                Order with customer from newstore origin:
                  summary: Order with originated in Newstore.
                  value:
                    id: GD000001234
                    placed_at: '2021-11-22T12:51:39.30Z'
                    channel_type: web
                    origin: newstore
                    origin_id: 6f38b75f-3fb3-4454-975d-af0cb412f8fa
                    status: in_fulfillment
                    currency: USD
                    fulfillment_type: traditional
                    customer:
                      id: e97f516a-8cce-447c-9757-8b54b84d8967
                      name: John Doe
                      email: johndoe@gmail.com
                    items:
                      - id: b9a144c2-3bd2-4066-983e-b2f2aa0c23ee
                        origin_id: b9a144c2-3bd2-4066-983e-b2f2aa0c23ee
                        status: in_fulfillment
                        price:
                          net: 72
                          tax: 7.2
                          gross: 79.2
                          discount: 10
                        product_attributes:
                          name: Kate Dress
                          size: M
                          color: red
                          image_url: https://image.com/dress.jpeg
                          additional_variant_1: Regular fit
                          additional_variant_2: Red with highlights
                        external_identifier:
                          sku: '1000016'
                          serial_number: SE-5678
                          product_id: '1000016'
                        discounts:
                          - level: item
                            value: 10
                            price_adjustment: 10
                            type: percentage
                    totals:
                      net: 72
                      tax: 7.2
                      gross: 79.2
                      total: 84.2
                      shipping: 5
                      discount: 10
                    payment_history:
                      - category: refund
                        amount: 77.58
                        currency: USD
                        method: cash
                      - category: payment
                        amount: 84.2
                        currency: USD
                        method: credit_card
                        payment_information: Visa (**** 1111)
                Order without customer:
                  summary: Order with a customer associated.
                  value:
                    id: GD000001234
                    placed_at: '2021-11-22T12:51:39.30Z'
                    channel_type: web
                    origin: newstore
                    origin_id: 6f38b75f-3fb3-4454-975d-af0cb412f8fa
                    status: in_fulfillment
                    currency: USD
                    fulfillment_type: traditional
                    items:
                      - id: product-agd6f4
                        origin_id: b9a144c2-3bd2-4066-983e-b2f2aa0c23ee
                        status: in_fulfillment
                        price:
                          net: 72
                          tax: 7.2
                          gross: 79.2
                          discount: 10
                        product_attributes:
                          name: Kate Dress
                          size: M
                          color: red
                          image_url: https://image.com/dress.jpeg
                          additional_variant_1: Regular fit
                          additional_variant_2: Red with highlights
                        external_identifier:
                          sku: '1000016'
                          serial_number: '7890'
                        discounts:
                          - level: item
                            value: 10
                            price_adjustment: 10
                            type: percentage
                    totals:
                      net: 72
                      tax: 7.2
                      gross: 79.2
                      total: 84.2
                      shipping: 5
                      discount: 10
                    payment_history:
                      - category: refund
                        amount: 77.58
                        currency: USD
                        method: cash
                      - category: payment
                        amount: 84.2
                        currency: USD
                        method: credit_card
                        payment_information: Visa (**** 1111)
                Order with tokenized customer PII:
                  summary: Order with tokenized customer PII.
                  value:
                    id: GD000001234
                    placed_at: '2021-11-22T12:51:39.30Z'
                    channel_type: web
                    origin: external
                    origin_id: GD000001234
                    status: in_fulfillment
                    currency: USD
                    fulfillment_type: traditional
                    customer:
                      id: >-
                        NS-EU-01FXX4SPXKPQCEWZWERZS9D7582-01FXX4SWFJKK66QGEEWQ8TRWPS
                      name: >-
                        NS-EU-01FXX4SPXKPQCEWZWERZS9D7582-01FXX4SWFJKK66QGEEWQ8TRWPQ
                      email: >-
                        NS-EU-01FXX4SPXKPQCEWZWERZS9D7582-01FXX4SWFJKK66QGEEWQ8TRWXS
                    items:
                      - id: '394329361530903'
                        origin_id: '394329361530903'
                        status: in_fulfillment
                        price:
                          net: 72
                          tax: 7.2
                          gross: 79.2
                          discount: 10
                        product_attributes:
                          name: Kate Dress
                          size: M
                          color: red
                          image_url: https://image.com/dress.jpeg
                          additional_variant_1: Regular fit
                          additional_variant_2: Red with highlights
                        external_identifier:
                          sku: '1000016'
                          serial_number: SE-1234
                          product_id: '1000016'
                        discounts:
                          - level: item
                            value: 10
                            price_adjustment: 10
                            type: percentage
                    totals:
                      net: 72
                      tax: 7.2
                      gross: 79.2
                      total: 84.2
                      shipping: 5
                      discount: 10
                    payment_history:
                      - category: refund
                        amount: 77.58
                        currency: USD
                        method: cash
                      - category: payment
                        amount: 84.2
                        currency: USD
                        method: credit_card
                        payment_information: Visa (**** 1111)
              schema:
                title: >-
                  Response body for getting order details from an external
                  system.
                type: object
                allOf:
                  - description: All common order and order item attributes.
                    type: object
                    required:
                      - id
                      - placed_at
                      - channel_type
                      - origin
                      - origin_id
                      - status
                      - currency
                      - fulfillment_type
                      - items
                    properties:
                      id:
                        type: string
                        minLength: 1
                        description: >-
                          The identifier of the order, it's the shared
                          identifier between NewStore and the external system.
                      placed_at:
                        type: string
                        format: date-time
                        description: >-
                          The time when the order was placed. It should follow
                          https://tools.ietf.org/html/rfc3339 in UTC.
                      channel_type:
                        type: string
                        enum:
                          - store
                          - web
                        minLength: 1
                        description: The channel through which the order was placed.
                      origin:
                        type: string
                        enum:
                          - newstore
                          - external
                        minLength: 1
                        description: >-
                          Describes in which Order Management System the order
                          originated from. [In-store
                          returns](https://docs.newstore.net/developers/guides/integ-eOMS/#in-store-returns)
                          are affected by the value of `origin`
                      origin_id:
                        type: string
                        minLength: 1
                        description: >-
                          The identifier of the order from the Order Management
                          System where it originated from. If it originated in
                          Newstore, it must be the UUID assigned to the order
                          during the order creation process.
                      status:
                        type: string
                        enum:
                          - pending
                          - in_fulfillment
                          - complete
                        minLength: 1
                        description: >-
                          The current status of the order. Specified as
                          `pending` when the order is in the grace period,
                          `in_fulfillment` if any of the item is currently being
                          fulfilled, and `complete` when the processing of all
                          items in the platform are considered complete, such as
                          when all items have been shipped, canceled or
                          returned.
                      currency:
                        type: string
                        minLength: 3
                        maxLength: 3
                        description: Currency code (ISO 4217) used in internal accounting
                      fulfillment_type:
                        type: string
                        enum:
                          - traditional
                          - same_day
                          - in_store_pickup
                          - in_store_purchase
                          - multiple
                        minLength: 1
                        description: >-
                          The fulfillment type of the order. In case of mixed
                          cart orders, fulfillment type is always 'multiple'
                      items:
                        type: array
                        minLength: 1
                        items:
                          type: object
                          required:
                            - id
                            - origin_id
                            - status
                            - price
                            - product_attributes
                          properties:
                            id:
                              type: string
                              minLength: 1
                              description: >-
                                The identifier of the product, this can be any
                                type of identifier from the external system and
                                should be unique per order item.
                            origin_id:
                              type: string
                              minLength: 1
                              description: >-
                                If the origin of the order is 'newstore', this
                                should be the order item UUID. If the order
                                originated in an external system, it should be
                                the identifier from the external system and is
                                the same as 'id'.
                            status:
                              type: string
                              enum:
                                - pending
                                - in_fulfillment
                                - complete
                                - cancelled
                                - returned
                            price:
                              type: object
                              required:
                                - gross
                                - net
                                - tax
                                - discount
                              properties:
                                gross:
                                  type: number
                                  description: The gross price of the item.
                                net:
                                  type: number
                                  description: The net price of the item.
                                tax:
                                  type: number
                                  description: The taxes of the item.
                                discount:
                                  type: number
                                  description: The applied discount to the item.
                            product_attributes:
                              type: object
                              required:
                                - name
                              properties:
                                name:
                                  type: string
                                  minLength: 1
                                  description: The name of the product.
                                size:
                                  type: string
                                  minLength: 1
                                  description: The size of the product.
                                color:
                                  type: string
                                  minLength: 1
                                  description: The color of the product.
                                image_url:
                                  type: string
                                  format: uri
                                  minLength: 1
                                  description: The URL to a product image.
                                additional_variant_1:
                                  type: string
                                  minLength: 1
                                  description: >-
                                    A free form field for additional product
                                    attributes.
                                additional_variant_2:
                                  type: string
                                  minLength: 1
                                  description: >-
                                    A free form field for additional product
                                    attributes.
                            external_identifier:
                              description: External identifiers for order item
                              type: object
                              properties:
                                '*':
                                  description: >-
                                    Any external identifier as specified in the
                                    catalog data, e.g. SKU, EAN and others.
                                  type: string
                                  minLength: 1
                                serial_number:
                                  description: Serial number for order item
                                  type: string
                                  minLength: 1
                                product_id:
                                  description: >-
                                    The identifier of the product from the
                                    NewStore catalog.
                                  type: string
                                  minLength: 1
                            discounts:
                              type: array
                              description: A list of applied discounts
                              minLength: 1
                              items:
                                type: object
                                required:
                                  - level
                                  - value
                                  - price_adjustment
                                  - type
                                properties:
                                  level:
                                    type: string
                                    enum:
                                      - item
                                      - order
                                    description: >-
                                      On which level the discount was applied,
                                      either on the entire order or only on this
                                      item.
                                  value:
                                    type: number
                                    minimum: 0
                                    description: >-
                                      If the discount is of type 'fixed', this
                                      is equal to the adjusted price amount. If
                                      the discount is of type 'percentage', this
                                      is the percentage, e.g. 20%.
                                  price_adjustment:
                                    type: number
                                    minimum: 0
                                    description: The applied discount.
                                  type:
                                    type: string
                                    enum:
                                      - fixed
                                      - percentage
                                    description: >-
                                      The type of the discount, either 'fixed'
                                      or 'percentage'.
                  - type: object
                    required:
                      - totals
                    properties:
                      customer:
                        type: object
                        properties:
                          id:
                            type: string
                            minLength: 1
                            description: The identifier of the customer.
                          name:
                            type: string
                            minLength: 1
                            description: The full name of the customer.
                          email:
                            type: string
                            format: email
                            minLength: 1
                            description: The email address of the customer.
                      totals:
                        type: object
                        required:
                          - gross
                          - net
                          - tax
                          - total
                          - discount
                          - shipping
                        properties:
                          gross:
                            type: number
                            description: >-
                              The gross price of the order, is the sum of all
                              item gross prices.
                          net:
                            type: number
                            description: >-
                              The net price of the order, is the sum of all item
                              net prices.
                          tax:
                            type: number
                            description: >-
                              The taxes of the order, is the sum of all item
                              taxes.
                          total:
                            type: number
                            description: >-
                              The total amount that the customer paid including
                              shipping costs, taxes, and any discounts.
                          discount:
                            type: number
                            description: The applied discount to the entire order.
                            minimum: 0
                          shipping:
                            type: number
                            description: The shipping amount.
                      payment_history:
                        type: array
                        minLength: 1
                        items:
                          type: object
                          required:
                            - category
                            - amount
                            - currency
                            - method
                          description: >-
                            Contains the payments/refunds history for the order.
                            Can also include multiple payments against multiple
                            credit sources (i.e. gift card + credit card)
                          properties:
                            category:
                              type: string
                              description: >-
                                Describes if it is a Payment (authorization or
                                capture) or Refund.
                              enum:
                                - payment
                                - refund
                            amount:
                              type: number
                              description: The monetary value of the payment/refund.
                              minimum: 0
                            currency:
                              description: >-
                                The currency of the amount as 3 character
                                ISO-4217 code. Example USD, EUR.
                              maxLength: 3
                              minLength: 3
                              type: string
                            method:
                              description: The method customer paid for the order.
                              type: string
                              enum:
                                - gift_card
                                - credit_card
                                - cash
                            payment_information:
                              type: string
                              description: >-
                                Any payment information related to the payment
                                method used. For example, it can contain the
                                card type along with the last 4 digits of the
                                credit card number.
                              example: Visa (**** 1111)
        '400':
          description: The request to fetch order details is malformed.
        '403':
          description: >-
            The request to fetch order details is unauthenticated or API Key is
            invalid.
        '404':
          description: The order with the given identifier couldn't be found.
        '500':
          description: >-
            Something went wrong on the server when requesting the order
            details.
        default:
          description: Unexpected Error
      description: >
        Requests details for the order with the given identifier from an
        external system.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The identifier of the order.
components: {}
